feat: scatter plot labeling options
datavisyn/visyn_core pull request #183
Opened 2024-02-19 11:28 UTC by dv-raghad-jamalaldeen

Closes #180 

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- add labels to scatter plot and provide three modes (Show labels for selected points, show all, hide all)

### Screenshots

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2024-02-20 16:08 UTC, dvchristianbors requested changes
Thanks for your PR. Code-wise the PR looks good. However, I found that when having no selection, and having selected the option to only show labels for the selection, then all labels are showing. I would expect this to be the opposite: If nothing is selected, do not show any labels.

Steps to reproduce:
1. Select Labels: 'Selected'
2. Do not select any points in the ranking/scatter plot

Expected result:
No labels showing

Actual result:
All labels showing
![image](https://github.com/datavisyn/visyn_core/assets/84898946/f2f6e501-2a41-46e7-8a67-531bdcc0f80f)

2024-02-20 16:43 UTC, thinkh requested changes
Thanks for the straight-forward implementation! 👍 It works already very well. I would like to see if we can improve the label position so that we avoid over plotting.

![grafik](https://github.com/datavisyn/visyn_core/assets/5851088/ab1306fa-e7fc-490e-bf1c-83169d96d9c8)

Furthermore, please change the behavior for the "selected" option:

* No item is selected -> no label shown (currently, it shows all labels)
* Some items are selected -> show label for selected items

Please also find some wording suggestions below.

P.S. Please add recent screenshots to your PR in the first comment. Thanks.

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/utils.ts
> +        textposition: 'top center',
Please check if you can improve the position of the labels by converting and applying the suggestion from this post: https://community.plotly.com/t/how-to-prevent-text-overlapping-between-traces/36770/4

That would alleviate situations like this:
 
![grafik](https://github.com/datavisyn/visyn_core/assets/5851088/413ad849-839c-4762-8a5f-443fc596d371)

If it works well, we could set the default option to "Selected" (instead of "never"/"off").

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/interfaces.ts
> +  OFF = 'Off',
I suggest to adapt the label and enums to:

```suggestion
  NEVER = 'Never',
  ALWAYS = 'Always',
  SELECTED = 'Selected',
```

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/LabelingOptions.tsx
> +          { label: ELabelingOptions.OFF, value: ELabelingOptions.OFF },
I suggest to adapt the label and enums to:

```suggestion
          { label: ELabelingOptions.NEVER, value: ELabelingOptions.NEVER },
          { label: ELabelingOptions.ALWAYS, value: ELabelingOptions.ALWAYS },
          { label: ELabelingOptions.SELECTED, value: ELabelingOptions.SELECTED },
```

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/LabelingOptions.tsx
> +    <Input.Wrapper label="Labels">
```suggestion
    <Input.Wrapper label="Show labels">
```

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/utils.ts
> +              textposition: 'top center',
See suggestion for improved text position above.

2024-02-20 16:43 UTC, thinkh commented on src/vis/scatter/utils.ts
> +  showLabels: ELabelingOptions.OFF,
If the improved label position works well, we could think of enabling this by default for selected items.

2024-02-21 07:11 UTC, dv-raghad-jamalaldeen commented
> Thanks for your PR. Code-wise the PR looks good. However, I found that when having no selection, and having selected the option to only show labels for the selection, then all labels are showing.
> 
> In my opinion, this should be the opposite: If nothing is selected, do not show any labels.
> 
> Steps to reproduce:
> 
> 1. Select Labels: 'Selected'
> 2. Do not select any points in the ranking/scatter plot
> 
> Expected result: No labels showing
> 
> Actual result: All labels showing ![image](https://private-user-images.githubusercontent.com/84898946/306336367-f2f6e501-2a41-46e7-8a67-531bdcc0f80f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTMxMTcsIm5iZiI6MTcwODQ1MjgxNywicGF0aCI6Ii84NDg5ODk0Ni8zMDYzMzYzNjctZjJmNmU1MDEtMmE0MS00NmU3LThhNjctNTMxYmRjYzBmODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE4MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjODEwNGFjMjI5NGEyMGM0Mjk1NTkzNzljMjlkNWU3MmZmODAxNWMyMTRiMmI0NjIyMmE2YTVlN2UxNzFiMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2jIDMfqoe6HHcL9hxG30Nf-4OHbNahxhsCtq5LjxwY)

Thanks! Actualy it is the default selection state, in this component from vis perspective everything is selected by default, and the brush is to deselect some, (colors also following this)
Now I'm following the data state instead,  solved in [31fa76f](https://github.com/datavisyn/visyn_core/pull/183/commits/31fa76fc434e2ae2ebd8b263049ce70e1d4cd922)

2024-02-21 08:51 UTC, dv-raghad-jamalaldeen commented on src/vis/scatter/utils.ts
> +        textposition: 'top center',
I applied it in [3a54b14](https://github.com/datavisyn/visyn_core/pull/183/commits/3a54b142753e5adc74737785ecfcd25b75c398b8), please let me know what do you think

2024-02-21 10:04 UTC, thinkh approved these changes
Thanks for addressing the feedback and also integrating the label positions. It works very well in my tests. We now have less occlusion, unless there are 3 or more points exactly on the same spot. 

![grafik](https://github.com/datavisyn/visyn_core/assets/5851088/a6838902-72ce-4838-ba2a-a26b62e645dc)

The "selected" behavior is also more intuitive now and works as I would expect it. 

![grafik](https://github.com/datavisyn/visyn_core/assets/5851088/18c65fe7-ab71-41fb-b396-527673cf8f06)

From my side this PR can be merged. 👍

2024-02-21 10:41 UTC, dvchristianbors approved these changes
Thank you for your changes. I agree with Holgers comments! The addition of changing the label color for selected items when showing all labels is great!

2024-02-21 11:52 UTC, merged