Add basic telemetry infrastructure
datavisyn/visyn_core pull request #2
Opened 2023-02-24 12:32 UTC by puehringer

Adds basic telemetry using opentelemetry, prometheus, tempo, loki, grafana, ...

## Screenshots
![image](https://user-images.githubusercontent.com/51900829/210381155-70dc0e53-153d-4f33-a8e7-f6253d3025b7.png)

2023-02-24 14:18 UTC, mstreit commented
Oh, really cool!

2023-07-04 07:02 UTC, thinkh commented on requirements_extras_telemetry.txt
> +python-logging-loki==0.3.1
Update versions in requirements.txt

2023-07-04 07:02 UTC, thinkh commented
https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-traces/opentelemetry-ingest/opent-python#tabgroup--instrument-application--without-oneagent

2023-07-07 07:20 UTC, thinkh commented on visyn_core/settings/model.py
> +    service_name: str
```suggestion
    service_name: str
    """
    Service name must be full qualified name (e.g., myapp.app.datavisyn.io)
    """
```

2023-07-18 07:15 UTC, thinkh requested changes
Please find my remarks below. I'd also suggest to add a Readme.md with the basic instructions how to set up and run the telemetry for an app and also for a local Docker setup.

2023-07-18 07:15 UTC, thinkh commented on visyn_core/middleware/fastapi_metrics_middleware.py
> +# TODO: This middleware is quite slow, it should be replaced with one similar to the ASGI instrumentor middleware
Is this something we should address now or do you want to create a follow-up issue?

2023-07-18 07:15 UTC, thinkh commented on visyn_core/settings/model.py
> +    file: str = "./fakeUsers.db"
What about this TODO?

2023-07-18 07:15 UTC, thinkh commented on visyn_core/tests/test_telemetry.py
> +                "enabled_plugins": ["tdp_core"],
```suggestion
            "visyn_core": {
                "enabled_plugins": ["visyn_core"],
```

Is it really still tdp_core?

2023-07-18 07:23 UTC, puehringer commented on visyn_core/settings/model.py
> +    file: str = "./fakeUsers.db"
This should have never been in this PR, was added by mistake. Will remove it.

2023-07-18 07:23 UTC, puehringer commented on visyn_core/tests/test_telemetry.py
> +                "enabled_plugins": ["tdp_core"],
Both works (it falls back to tdp_core if visyn_core key is not found), but more correct is visyn_core. Will change it.

2023-07-18 07:53 UTC, puehringer commented on visyn_core/middleware/fastapi_metrics_middleware.py
> +# TODO: This middleware is quite slow, it should be replaced with one similar to the ASGI instrumentor middleware
It's still very fast, but FastAPI/starlette HTTPMiddleware is slower than the "raw" middleware. Nothing to be fixed however, only when it becomes a problem (which it isn't yet).

2023-07-18 08:56 UTC, thinkh approved these changes
Thanks for integrating the feedback. Looks good to me. 👍

2023-07-18 09:02 UTC, merged