Mweigl/scattervis regression
datavisyn/visyn_core pull request #275
Opened 2024-04-26 07:38 UTC by dvmartinweigl

Closes 
https://github.com/datavisyn/reprovisyn/issues/342
https://github.com/datavisyn/bioinsight/issues/357

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes
- Added faceting support on categorical columns
- Added option to show regression lines to scatterplot
  - also supported in plot matrix and facteing
  - multiple models: linear, polynomial (with order 2-5), exponential, logarithmic, power
  - added some stats/metrics: r², correlation coefficient, n
- added story for linear regression
- renamed `multiples` option to `facets` as it was confusing to users 

### Screenshots

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2024-04-26 09:19 UTC, dvdanielamoitzi commented on src/vis/scatter/Regression.tsx
> +export enum ERegressionLineType {
@dvmartinweigl  please move the exported interfaces / enums which should be available in other apps to the interfaces.ts file so that i is exported correctly and can be imported in other apps

2024-05-06 12:13 UTC, oltionchampari reviewed
In general it works, just a couple of things

1. Missing category is interpreted as `new text`?
![image](https://github.com/datavisyn/visyn_core/assets/51322092/63ae8981-9ac6-4164-a758-62e00629127e)

2. The facets select should allow only categorical columns?

3. The only case in which this provides any value in ordino is when you select a column with  < 5 categories, any other column in ordino freezes the application and the traces overlap each other because we have 30 + categories i.e., tumortype, organ

![image](https://github.com/datavisyn/visyn_core/assets/51322092/f7c3de0d-a84f-4d54-9c1d-15222e36442a)

4. Performance difference between bar chart and scatter plot when selecting the same column as facet is huge (bar chart is quite good)

2024-05-08 12:29 UTC, oltionchampari requested changes
One more thing i noticed that you are allowed to choose any degree polynomial

![gr](https://github.com/datavisyn/visyn_core/assets/51322092/25dd4727-1813-4a5c-99b6-a77dbcb4c324)

Prefer maybe a segmented control with options: Quadratic, Cubic

2024-05-08 15:13 UTC, dvmartinweigl commented
> In general it works, just a couple of things
> 
> 1. Missing category is interpreted as `new text`?
>    ![image](https://private-user-images.githubusercontent.com/51322092/328171866-63ae8981-9ac6-4164-a758-62e00629127e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODE0MzYsIm5iZiI6MTcxNTE4MTEzNiwicGF0aCI6Ii81MTMyMjA5Mi8zMjgxNzE4NjYtNjNhZTg5ODEtOWFjNi00MTY0LWE3NTgtNjJlMDA2MjkxMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmI2Y2ExYzhiZmVhYjE1ZTliNDIzZGRhZTYyNGM3YjI2OTE5N2M2MGFmNjNiOWQxYTZjMjE1OGFmNzlmYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGcae0552-4mesX6EJXUdlKJ47rcYavGUWBL6Tu7oEI)
> 2. The facets select should allow only categorical columns?
> 3. The only case in which this provides any value in ordino is when you select a column with  < 5 categories, any other column in ordino freezes the application and the traces overlap each other because we have 30 + categories i.e., tumortype, organ
> 
> ![image](https://private-user-images.githubusercontent.com/51322092/328171764-f7c3de0d-a84f-4d54-9c1d-15222e36442a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODE0MzYsIm5iZiI6MTcxNTE4MTEzNiwicGF0aCI6Ii81MTMyMjA5Mi8zMjgxNzE3NjQtZjdjM2RlMGQtYTg0Zi00ZDU0LTljMWQtMTUyMjJlMzY0NDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1MTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDcxYmJiZmY0MDg3OGEyYjhjMDNlNWQ3MWI2NzE5ODY0ODZiYWE4MzY2NjQxZmU4ODBjZjI2YTI1ODg0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XbrcbSBMmT12HV62FXKRYmMEwZwy9Juc24XwBIi-SdE)
> 
> 4. Performance difference between bar chart and scatter plot when selecting the same column as facet is huge (bar chart is quite good)

Should all be fixed :+1:

2024-05-08 15:15 UTC, dvdanielamoitzi approved these changes

2024-05-08 15:19 UTC, dvmartinweigl commented
Changed the sidebar to only support quadratic and cubic order for the polynom fit.

![image](https://github.com/datavisyn/visyn_core/assets/101096478/ad374e87-6840-4587-9dcf-9c5fc6e03c7a)

2024-05-08 15:23 UTC, dvmartinweigl commented on src/vis/scatter/interfaces.ts
> +  // EXPONENTIAL = 'Exponential',
disabled some of the line fit types as there seems to be an error with Math.log of negative values
see: https://github.com/Tom-Alexander/regression-js/issues/117

Maybe we could take another look and fix this

2024-05-13 12:04 UTC, dvchristianbors requested changes
Thanks for this PR. Generally, it looks good to me, however, I found an issue when selecting a facet category that contains missing data:
It will crash the plot.

![image](https://github.com/datavisyn/visyn_core/assets/84898946/feb0696b-3d6a-476c-8c01-a6c687714322)
![image](https://github.com/datavisyn/visyn_core/assets/84898946/feb0696b-3d6a-476c-8c01-a6c687714322)

I also noticed that the legend for a missing color category will show as `(trace 1)`.
![image](https://github.com/datavisyn/visyn_core/assets/84898946/8a0b7206-2123-4e7c-a981-78d1a8917f1b)
![image](https://github.com/datavisyn/visyn_core/assets/84898946/8a0b7206-2123-4e7c-a981-78d1a8917f1b)

Steps to reproduce:
1. Remove the species tag from a data entry in the iris dataset (`irisData.ts`).
  ```
  { ..., species: null }
  ```
2. Select Facet: _species_

2024-05-14 13:56 UTC, oltionchampari approved these changes

2024-05-14 14:05 UTC, dvchristianbors approved these changes

2024-05-14 14:09 UTC, dvdanielamoitzi approved these changes

2024-05-14 14:10 UTC, merged