feat: add toggle legend switch to scatter plot
datavisyn/visyn_core pull request #277
Opened 2024-04-29 08:51 UTC by oltionchampari

Closes https://github.com/datavisyn/visyn_core/issues/274

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- add toggle legend switch to scatter plot

### Screenshots

![gr](https://github.com/datavisyn/visyn_core/assets/51322092/73cab8ba-b85d-40e6-8fb1-898909ef39e1)

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2024-04-30 05:20 UTC, dvchristianbors requested changes
Thanks for you changes. Works as intended!
I have a small reuqest: Could you please move the Legend text closer to the toggle? When directly next to the settings icon, it almost looks like it belongs to the settings instead of the toggle button.
![image](https://github.com/datavisyn/visyn_core/assets/84898946/c95ecb3e-5f5b-4d5d-b561-ee7e94d22615)

2024-05-21 10:26 UTC, dvchristianbors requested changes
Please also resolve the conflicts with the develop branch.

2024-05-21 13:17 UTC, dvmartinweigl commented
In bioinsight we currently have the statistics on position absolute, covering your legend toggle.
We shoud whether render the stats somewhere else in bioinsight, or you add a z-index to your toggle?
![image](https://github.com/datavisyn/visyn_core/assets/101096478/d8e5b463-7282-4451-9221-64b731a899b7)

2024-05-23 10:57 UTC, dvchristianbors approved these changes

2024-05-23 11:28 UTC, dvchristianbors approved these changes

2024-05-23 11:28 UTC, merged