feat: take snapshot of visualization
datavisyn/visyn_core pull request #279
Opened 2024-04-29 08:56 UTC by oltionchampari

Closes *list issues numbers here*

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- 

### Screenshots

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

2024-05-08 14:21 UTC, dvdanielamoitzi commented
That's a great improvement, thanks for this PR @oltionchampari ! :muscle: 
I noticed a small thing during testing: When I download a screenshot from plotly visualizaions (e.g. scatter plot or violin plot), the name is Scatterplot.png.png (it has the .png suffix twice).

2024-05-08 14:55 UTC, dvmartinweigl commented
Really nice feature @oltionchampari !!
One thing that came to my mind ... would it maybe make sense to just always generate our own `uniquePlotId` internally? This would save us from having to pass it to the vis? You could also use `uuid4` instead of lodash uniqueId.

2024-05-13 10:38 UTC, thinkh requested changes
I tested the feature with this demo app and it works as expected. I fixed some things on the fly but still have a few more comments and suggestions below that could be addressed but they are not critical if we need to merge today.

2024-05-13 10:38 UTC, thinkh commented on package.json
> +    "html-to-image": "^1.11.11",
We must be aware that the download feature might have slow performance for large DOM trees, i.e., large visualizations.

> It's tested on latest Chrome, Firefox and Safari (49, 45 and 16 respectively at the time of writing), with Chrome performing significantly better on big DOM trees, possibly due to it's more performant SVG support, and the fact that it supports CSSStyleDeclaration.cssText property.
>
> Rendering will failed on huge DOM due to the dataURI limit varies.


See documentation:
* https://github.com/bubkoo/html-to-image?tab=readme-ov-file#browsers
* https://github.com/bubkoo/html-to-image?tab=readme-ov-file#things-to-watch-out-for

2024-05-13 10:38 UTC, thinkh commented on src/vis/correlation/CorrelationVis.tsx
> +export function CorrelationVis({ config, columns, ...rest }: ICommonVisProps<ICorrelationConfig>) {
Why do you use the `...rest` syntax here? I would align it with the other visualizations where you explicitly add the props `uniquePlotId` and `showDownloadScreenshot` (e.g., RaincloudVis).

2024-05-13 10:38 UTC, thinkh commented on src/vis/bar/BarVis.tsx
> +export function BarVis({ config, columns, selectionCallback = () => null, selectedMap = {}, selectedList = [], ...rest }: ICommonVisProps<IBarConfig>) {
Why do you use the `...rest` syntax here? I would align it with the other visualizations where you explicitly add the props `uniquePlotId` and `showDownloadScreenshot` (e.g., RaincloudVis).

2024-05-13 10:38 UTC, thinkh commented on src/vis/interfaces.ts
> +  uniquePlotId?: string;
> One thing that came to my mind ... would it maybe make sense to just always generate our own uniquePlotId internally? This would save us from having to pass it to the vis?

@dvmartinweigl The `uniquePlotId` is optional here. Does this [resolve your comment](https://github.com/datavisyn/visyn_core/pull/279#issuecomment-2100778587)? 

> You could also use uuid4 instead of lodash uniqueId.

Yes, that would be an option but would also add uuidv4 as a dependency. I think it is not necessary to add a new dependency for this.

2024-05-14 07:31 UTC, oltionchampari commented on src/vis/correlation/CorrelationVis.tsx
> +export function CorrelationVis({ config, columns, ...rest }: ICommonVisProps<ICorrelationConfig>) {
The type of the child component was not correctly typed so with rest you did not have to fix the type.
I added the exact props now.

2024-05-14 07:31 UTC, oltionchampari commented on src/vis/bar/BarVis.tsx
> +export function BarVis({ config, columns, selectionCallback = () => null, selectedMap = {}, selectedList = [], ...rest }: ICommonVisProps<IBarConfig>) {
See above answer

2024-05-14 07:33 UTC, oltionchampari commented
> One thing that came to my mind ... would it maybe make sense to just always generate our own `uniquePlotId` internally

The problem with this Martin is that in case you want to render your own download button outside the vis you have now way to get that id

2024-05-14 07:33 UTC, oltionchampari commented on src/vis/interfaces.ts
> +  uniquePlotId?: string;
I agree

2024-05-14 07:35 UTC, oltionchampari commented on package.json
> +    "html-to-image": "^1.11.11",
Thanks for info @thinkh. I will do another stress test for this in ordino

2024-05-14 07:48 UTC, oltionchampari commented on package.json
> +    "html-to-image": "^1.11.11",
See below a test  in ordino with barchart with multiples selected. There is definitely a waiting time but still acceptable i would say.

![gr](https://github.com/datavisyn/visyn_core/assets/51322092/45ecb586-1282-46f5-8bc8-518a72995c21)

2024-05-14 07:55 UTC, puehringer commented on src/vis/EagerVis.tsx
> +  uniquePlotId?: string;
@oltionchampari 
Two questions here: 

- Why is this id not simply generated by the EagerVis? I.e. is there any benefit of passing it? One could simply `useMemo(() => uniqueId(), [])` or uuid4 or anything like it in the component here?
- Why isn't a ref used? A ref would be a reference to a DOM element instead of a `querySelector` in the hook...

2024-05-14 07:58 UTC, oltionchampari commented on src/vis/EagerVis.tsx
> +  uniquePlotId?: string;
One of the requirements, is that applications render their own toolbars, and they need a way to trigger a download of a screenshot outside of the vis see https://github.com/datavisyn/bioinsight/pull/401/files

2024-05-14 09:40 UTC, dvdanielamoitzi commented on src/vis/general/DownloadPlotButton.tsx
> +        <i className="fa-solid fa-camera" />
I have now introduced the new download visualization icon:
![image](https://github.com/datavisyn/visyn_core/assets/57343176/01312abb-7f09-4ff6-90e1-771991dd7708)

2024-05-14 10:05 UTC, thinkh approved these changes
Thanks for the changes. Looks good from my side. Waiting for @puehringer last feedback then we can merge this PR. 🚀

2024-05-14 11:04 UTC, merged