fix: bar chart facets horizontal scrollbar
datavisyn/visyn_core pull request #480
Opened 2024-08-21 07:55 UTC by dv-usama-ansari

Closes https://github.com/datavisyn/communication_xaira_ordino/issues/26

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [x] Requires UI/UX/Vis review
  - [x] Reviewer(s) are notified @oltionchampari
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [x] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- Fix scroll issue in faceting of the bar charts

### Screenshots
![xiara-26-bar-chart-facet-fix](https://github.com/user-attachments/assets/10fac33f-f912-4d4e-98ea-f66da6779b9a)

### Additional notes for the reviewer(s)

-  There is a slight flicker when the container resizes. This can be minimized visually by adding a loading overlay when the container is resizing. The loading overlay logic is in the commented code

2024-08-27 08:57 UTC, dvmoritzschoefl requested changes

2024-08-27 08:57 UTC, dvmoritzschoefl commented on src/vis/bar/BarChart.tsx
> +        <ScrollArea.Autosize h={containerHeight} style={{ overflowX: 'hidden' }}>
ScrollArea already has a inbuilt way of specifying which scrollbars to show, also do we need an autosizing scrollarea when we do not set the maximum width/height?

```suggestion
        <ScrollArea.Autosize  h={containerHeight} w={containerWidth} scrollbars="y">
```

2024-08-27 14:10 UTC, dv-usama-ansari commented on src/vis/bar/BarChart.tsx
> +        <ScrollArea.Autosize h={containerHeight} style={{ overflowX: 'hidden' }}>
This works as expected. Thanks for the suggestion!

2024-08-29 09:19 UTC, dv-usama-ansari commented
Storybook has been fixed in https://github.com/datavisyn/visyn_core/pull/480/commits/186c6a80ed1840083b80470a9c451c546002a86c
![image](https://github.com/user-attachments/assets/357b105f-eb4f-45d7-8854-00731aebd832)
![Screenshot from 2024-08-29 11-18-48](https://github.com/user-attachments/assets/47f5615c-62c6-4a7f-9dcb-0a436b2bc090)

2024-08-29 12:10 UTC, merged