feat: implement bar plot sorting
datavisyn/visyn_core pull request #482
Opened 2024-08-26 13:55 UTC by dv-usama-ansari

Closes https://github.com/datavisyn/communication_xaira_ordino/issues/28

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [x] Requires UI/UX/Vis review
  - [x] Reviewer(s) are notified @thinkh @puehringer 
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [x] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes
- Add sorting to the bar charts implementation in echarts
- All the plots can be sorted at once with the sort icon in the header
  - Currently the plots in faceted view cannot be sorted individually
- Plots are arranged in descending order by default (configurable sorting)
- Facets are arranged in ascending order

### Screenshots
![image](https://github.com/user-attachments/assets/caf5bdf2-72ab-4455-9dbb-d515e8b7056b)

### Additional notes for the reviewer(s)

- N/A

2024-08-27 11:21 UTC, dvmoritzschoefl requested changes

2024-08-27 11:21 UTC, dvmoritzschoefl commented on src/vis/bar/BarChartSortButton.tsx
> +  const { tooltipLabel, icon, color, nextSortState } = useMemo(() => {
```suggestion
  const { tooltipLabel, icon, color, nextSortState } = React.useMemo(() => {
```

2024-08-27 11:21 UTC, dvmoritzschoefl commented on src/vis/bar/SingleEChartsBarChart.tsx
> +      setXAxis({ type: 'value' });
this looks very dangerous in conjunction with the useEffect on the top that relies on x and y axis, since one render will contain an inconsistent state. maybe this can be merged somehow. two easy ways i can think of is useSetState from mantine or just make an object with { xAxis, yAxis..}

2024-08-27 11:35 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +            text: selectedFacetValue || null,
Since this is an optional property, not doing `|| null` would set `text: undefined` which crashes the component.

2024-08-27 11:38 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +
This is added by @thinkh and he plans to use it later in the development. Please let's not remove this prop for now.

2024-08-27 11:40 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +const normalizedValue = ({ config, value, total }: { config: IBarConfig; value: number; total: number }) =>
The total can be zero, which is why we do not see any bars when a different aggregation type (Min, Max, Avg, Median) is selected.

2024-08-27 12:23 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
>  const AXIS_LABEL_MAX_LENGTH = 50;
Used it in axis labels.

2024-08-27 12:24 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +      setXAxis({ type: 'value' });
Converted to an object (see L75)

2024-08-27 13:55 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +                return { ...itemClone, data: sortedDataWithCategories.map((d) => d.value) };
This is required because the type definition of `BarSeriesOption` does not have `categories` property in it, but the actual data has `categories` property which is required to update the axis when sorting takes place.

2024-08-28 09:39 UTC, dvmoritzschoefl commented on src/vis/bar/SingleEChartsBarChart.tsx
> +const normalizedValue = ({ config, value, total }: { config: IBarConfig; value: number; total: number }) =>
the reason you dont see bars is that the data is actual 0 for expression data. for other columns it works as expected

2024-08-28 09:42 UTC, dvmoritzschoefl approved these changes

2024-08-29 09:19 UTC, dv-usama-ansari commented
Storybook has been fixed in https://github.com/datavisyn/visyn_core/pull/482/commits/066ade7e534fb6577499bebfdc86656ebf32e6d8
![image](https://github.com/user-attachments/assets/357b105f-eb4f-45d7-8854-00731aebd832)
![Screenshot from 2024-08-29 11-18-48](https://github.com/user-attachments/assets/47f5615c-62c6-4a7f-9dcb-0a436b2bc090)

2024-08-29 12:10 UTC, puehringer commented
@dv-usama-ansari the PR looks good, but there's a conflict with the previously merged one. Can you resolve it please? Then we can continue merging it.

2024-08-29 12:19 UTC, merged