fix: bar chart follow up bugs
datavisyn/visyn_core pull request #575
Opened 2024-10-18 06:49 UTC by dv-usama-ansari

Closes #563

### Developer Checklist (Definition of Done)

**Issue**

- [x] All acceptance criteria from the issue are met
- [x] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [x] Requires UI/UX/Vis review
  - [x] Reviewer(s) are notified @datavisyn/core @thinkh 
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [x] Branch is up-to-date with the branch to be merged with, i.e., develop
- [x] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [x] Descriptive title for this pull request is provided (will be used for release notes later)
- [x] Reviewer and assignees are defined
- [x] Add type label (e.g., *bug*, *feature*) to this pull request
- [x] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [x] The PR is connected to the corresponding issue (via `Closes #...`)
- [x] [Summary of changes](#summary-of-changes) is written

### Summary of changes
- Addresses bugs mentioned in #563 and its comments

### Screenshots
- N/A

### Additional notes for the reviewer(s)
- N/A

2024-10-18 07:04 UTC, thinkh commented on package.json
> +    "comlink": "^4.4.1",
@puehringer Since you've worked with `comlink` before, is the minor version range fine or should we switch to `patch` level?

2024-10-18 07:23 UTC, thinkh reviewed
Just a quick intermediate review without testing it yet.

2024-10-18 07:23 UTC, thinkh commented on src/vis/bar/SingleEChartsBarChart.tsx
> +      // const result = generateBarSeries(serializedData, serializedConfig);
Remove?

2024-10-18 09:30 UTC, dv-usama-ansari commented
Handled cases where too many bars are displayed:
![Screenshot from 2024-10-18 11-27-34](https://github.com/user-attachments/assets/648b92b9-4921-4732-b716-ac217a3562c1)

> NOTE: This message is not displayed initially, but only when all the computation is done and the number of bars are calculated. Therefore it takes some time to show.

Handled case where there is no data to display:
![Screenshot from 2024-10-18 11-28-52](https://github.com/user-attachments/assets/ae4880f2-aaf7-454f-a923-c227edd8ba47)

2024-10-18 10:55 UTC, thinkh requested changes
The bar is not highlighted when I click on a bar to select the items. The items itself however, are selected.

![image](https://github.com/user-attachments/assets/75856254-973b-4e0f-8424-50c5c726f879)

2024-10-18 14:55 UTC, dv-usama-ansari commented
> The bar is not highlighted when I click on a bar to select the items. The items itself however, are selected.

Fixed in https://github.com/datavisyn/visyn_core/pull/575/commits/60cbc938873b3ec43d4657dcd9eb7bcbf5ccef68

2024-10-18 19:29 UTC, thinkh requested changes
The selection works now but no data is displayed when using this branch in Ordino!

![image](https://github.com/user-attachments/assets/3148dba9-b7d3-4864-8887-b0a673ee6354)

I added this branch as resolution in Ordino and started the demo landscape. Previous to this PR the count bar charts was displayed. 

@dv-usama-ansari Any idea what could be the problem here and how to solve it?

2024-10-18 20:04 UTC, thinkh commented on src/vis/bar/BarChart.tsx
> +  }, []);
I investigated the [reported problem](https://github.com/datavisyn/visyn_core/pull/575#pullrequestreview-2378838447) a bit and saw that the `generateAggregatedDataLookup` is not called inside the worker. Executing the function directly returns the aggregated data:

```ts
  const aggregator = React.useCallback(async (...args: Parameters<GenerateAggregatedDataLookup['generateAggregatedDataLookup']>) => {
    // return WorkerWrapper.generateAggregatedDataLookup(...args);
    return Promise.resolve(generateAggregatedDataLookup(...args));
  }, []);
```

Hence, my assumption is that the worker file is not bundled by rspack when it is part of a (transitive) dependency. It works when bundling visyn_core but not in Ordino where visyn_core is a dependency.

@puehringer Did you experience this bundling problem? Any idea how to solve this?

2024-10-18 20:06 UTC, thinkh commented on src/vis/bar/SingleEChartsBarChart.tsx
> +    if (groupSortedSeries.length > 0) {
Even when I call the aggregation function without a worker (see my previous comment), there seems to be a problem in the `groupSortedSeries` because it is still empty and prevents the display of the bar chart.

![image](https://github.com/user-attachments/assets/68e36a4d-2765-4394-bb61-0d66bf3da58b)

@dv-usama-ansari Any idea where this could be?

2024-10-21 07:29 UTC, dv-usama-ansari commented on src/vis/bar/SingleEChartsBarChart.tsx
> +    if (groupSortedSeries.length > 0) {
I would investigate this :+1:

2024-10-23 19:31 UTC, thinkh commented on src/vis/bar/SingleEChartsBarChart.tsx
> +    if (groupSortedSeries.length > 0) {
Fixed

2024-10-24 09:43 UTC, thinkh approved these changes
Looks good to me! 🚀

2024-10-24 10:10 UTC, dv-usama-ansari commented
> Looks good to me! 🚀

Also beautiful

![image](https://github.com/user-attachments/assets/93d99abb-ef56-406b-825b-b7a20603fbf5)

2024-10-24 11:04 UTC, merged