Added `useAnimatedTransform` hook
datavisyn/visyn_core pull request #620
Opened 2024-11-05 12:21 UTC by dvmoritzschoefl

- Added hook that returns a "animate" function that can interpolate between two keyframes.
- Can be used for animating when the user brushes a given area.

2024-11-05 14:33 UTC, thinkh requested changes
@dvmoritzschoefl thanks for the feature. Please add some documentation for future developers. Thanks.

2024-11-05 14:33 UTC, thinkh commented on src/vis/vishooks/hooks/useAnimatedTransform.ts
> +export function useAnimatedTransform({ onIntermediate }: { onIntermediate: (intermediateTransform: ZoomTransform) => void }) {
Please add some documentation what this hook does and what it can be used for. If possible, add some simple example. Thanks.

2024-11-05 20:52 UTC, dvmoritzschoefl commented on src/vis/vishooks/hooks/useAnimatedTransform.ts
> +export function useAnimatedTransform({ onIntermediate }: { onIntermediate: (intermediateTransform: ZoomTransform) => void }) {
Do you mean JSDoc style? As for an example there is already a storybook example with a toggle button that shows how this hook works.

2024-11-06 07:53 UTC, thinkh commented on src/vis/vishooks/hooks/useAnimatedTransform.ts
> +export function useAnimatedTransform({ onIntermediate }: { onIntermediate: (intermediateTransform: ZoomTransform) => void }) {
Yes, JSDoc for developers that want to use the hook outside of visyn_core. The example as Storybook is sufficient no need for an JSDoc example then.

2024-11-06 08:22 UTC, thinkh submitted a review, later dismissed

2024-11-06 09:00 UTC, thinkh approved these changes

2024-11-06 09:00 UTC, merged