Combine VIS PRs and refactor provider
datavisyn/visyn_core pull request #76
Opened 2023-08-14 06:09 UTC by dvmoritzschoefl

2023-08-25 08:59 UTC, dvchristianbors requested changes
I summarize my observations on the new vis here:

#### Multiple vis components
Bar plot, sankey plot, hexbin plot:
* Can we add categorical colors in the props so that we can match colors between lineup and the general vis (this already used to work for bar charts, and is working for scatter plot)?

#### Raincloud plot:
* The boxplot whiskers are inconsistent with the violin plot. How is it defined? min-max? It looks like the violin plot's boxplot spans the IQR.
  ![image](https://github.com/datavisyn/visyn_core/assets/84898946/e1715966-4c95-4e42-a768-03c59f0ab81d)
  ![Screenshot 2023-08-25 102414](https://github.com/datavisyn/visyn_core/assets/84898946/fbf12df8-5029-4f99-9ea3-c4cafbab2e78)
* With some score columns, the app breaks due to a `querySelector` error (EDIT: I think this is only due to some Ordino related adjustments that still need to be made)
  ![Screenshot 2023-08-25 095157](https://github.com/datavisyn/visyn_core/assets/84898946/17892203-de06-4585-a463-ae281ef94e2f)



#### Sankey plot
* instructions are not styled
  ![image](https://github.com/datavisyn/visyn_core/assets/84898946/ad124037-eb5a-453c-9ef7-9cbb467835e6)
  Use an error/warning boundary, similar to scatter plot warning
  ![image](https://github.com/datavisyn/visyn_core/assets/84898946/6264edb7-5507-4eea-9012-613465312dcf)

  

* plotly default (?) icons show in the canvas
  ![image](https://github.com/datavisyn/visyn_core/assets/84898946/617b4154-9a5e-4e2d-83f6-1be75bd53be0)

#### Correlation plot
* Sometimes a rogue correlation dot appears after removing a value column
  https://github.com/datavisyn/visyn_core/assets/84898946/8ae49590-eac1-4a2f-ab2d-828ffedb7414

2023-08-28 10:19 UTC, dvdanielamoitzi commented
We're using the following interfaces / enums which are not exported anymore:
EBarDirection, EBarDisplayType, EBarGroupingType, IBarConfig. We defenitely need IBarConfig

2023-08-28 13:26 UTC, dvchristianbors commented
> We're using the following interfaces / enums which are not exported anymore: EBarDirection, EBarDisplayType, EBarGroupingType, IBarConfig. We defenitely need IBarConfig

In Reprovisyn, we are using all specific vis configs. If this is not recommended, please let us know what to change in reprovisyn.

2023-09-12 12:33 UTC, thinkh commented
@dvmoritzschoefl Thanks for the latest refactoring and fixing the Ordino integration. Regarding the status of this PR: Did you address the [Bob's feedback](https://github.com/datavisyn/visyn_core/pull/76#pullrequestreview-1595266608) already?

I still see the plotly toolbar in the sankey diagram and in addition to that I would like to zoom and pan in this plot. Could you add this?

2023-09-21 09:28 UTC, dvmartinweigl commented
Could you please limit the x-axis label length and add a `text-overflow: ellipsis`
Otherwise the actual plot area becomes really small (see the screenshot)  

![image](https://github.com/datavisyn/visyn_core/assets/101096478/e8907ea7-9c60-423a-8645-6c9d4d02f7e0)

2023-09-22 10:17 UTC, dvmoritzschoefl commented
> Could you please limit the x-axis label length and add a `text-overflow: ellipsis` Otherwise the actual plot area becomes really small (see the screenshot)
> 
> ![image](https://user-images.githubusercontent.com/101096478/269563402-e8907ea7-9c60-423a-8645-6c9d4d02f7e0.png)

I do not see an easy way to do this. I also think this is out of scope for this PR which is only there to combine the existing vis into one framework. (Except the bug was introduced in this PR of course)

2023-09-22 10:25 UTC, dvmoritzschoefl commented
> #### Some other bugs I found while testing your branch in bioinisght:
> * For the column selection (numerical and categorical) we had a tool tip with `name` + `description` before. Now it is missing
> * The y-axis labesl of the bar chart should all be left aligned
>   ![Screenshot from 2023-09-21 14-41-30](https://user-images.githubusercontent.com/101096478/269662967-bb631028-3ed6-40b3-bb2d-5d309f677287.png)
> * The hexbin plot does not resize vertically when i reduce the mosaic height in bioinisight
>   ![Screenshot from 2023-09-21 14-43-39](https://user-images.githubusercontent.com/101096478/269664094-b0d87ef3-be25-4e6b-a7cd-ceec793ad86d.png)

the default for most vis frameworks is to right align items on the y axis, which is what makes most sense. what you see here is an artefact of the ellipsis which is hardcoded in the barchart (and not responsive like in plotly)

as for the hexbin plot yes, it does not seem to resize at all when the area is shrinking i will take a look at that

2023-09-25 08:31 UTC, thinkh commented on tsconfig.json
> +    "jsx": "react",
```suggestion
```

Can we remove this line? It is already the default in visyn_scripts:

https://github.com/datavisyn/visyn_scripts/blob/0d633022e00dd78c26da00e1b7716cff3a6ba828/config/tsconfig.template.json#L10C5-L10C6

2023-09-25 08:33 UTC, thinkh commented on package.json
> +    "chromatic": "^6.19.9",
I think chromatic should be moved to the `devDependencies`. Do you agree?

2023-09-26 13:05 UTC, dvdanielamoitzi commented
In the previous version we had a tooltip for categorical / numerical columns that we used in BioInsight to display more information on the selected items:
![image](https://github.com/datavisyn/visyn_core/assets/57343176/f3670d57-d5e2-41e2-88d4-57cb3d268c7d)

2023-09-27 08:57 UTC, dvchristianbors commented
> In the previous version we had a tooltip for categorical / numerical columns that we used in BioInsight to display more information on the selected items: ![image](https://user-images.githubusercontent.com/57343176/270664673-f3670d57-d5e2-41e2-88d4-57cb3d268c7d.png)

@dvdanielamoitzi  I'm a bit confused, did this use to work but it does not work any more? I just tried this in Reprovisyn, and the tooltip works as expected:
![image](https://github.com/datavisyn/visyn_core/assets/84898946/1e658f42-56e7-4873-8b41-ea3f1ebc146c)

2023-09-27 11:49 UTC, dvchristianbors approved these changes
The PR now looks good to me. I tested it with Ordino Enterprise and could not find any critical issues.

2023-09-27 12:27 UTC, dvmartinweigl approved these changes
Tested all the vis plots in Bioinisght and found no critical bugs. So this one is ready to merge from my perspective.

2023-09-27 12:36 UTC, merged